# Data sources

In order to analyze and gain some insights from the cryptocurrency market, out team chose seven types of popular cryptocurrencies stocks in this project. The chosen cryptos are `Bitcoin`, `Cardano`, `Dogecoin`, `EthereumClassic`, `Ethereum`, `ReneSola` and `XRP`. These cryptos all have large "market cup" (calcualted by multiplying the price by the number of coins in circulation), which reflect the popularity of the cryptos. After the researching, our team found that the cryptocurrency market became more stable and mature after the year of 2017 compared to the earlier stage. Thus, we decided to use the data from 1/1/2018 to 12/31/2020. 

To collect the stocks' data, one of our teammate Candong pulled it from `Yahoo Finance`, which is a reliable and well-known platform for stocks. In the `Historical Data` session for each stock, we could apply the filter to select the range of date that we want. And then, we could download the each of the stock separately into `csv` files. Since we have the same range of date for all selected stock, the number of entries of each stock are expected to be the same, which is around 1100 records. Each of the stock would have 7 columns. The column names and the descriptions are as listed below.  

| Column      | Data Type | Description   |
| ----------- | --------- | ------------- |
| Date        | Date      | Year-Month-Day|
| Open        | Numeric   | Open price of the stock |
| High        | Numeric   | Highest price of the stock in this date |
| Low         | Numeric   | Lowest price of the stock in this date |
| Close       | Numeric   | Close price of the stock |
| Adj Close   | Numeric   | The adjusted close price of the stock |
| Volumne     | Numeric   | Number of share traded in this date for the stock |

As we preprocess the data and investigate it, we found that the number of records for `ReneSola` doesn't match other stocks'. Having inconsistant number of records would be difficult for us to perform the analysis for this set of cryptos. The detailed information would be described in the `Missing Data` session.