# Interactive component

In this project, the team created two interactive plots to better show the relationship of the six cryptocurrencies. 

## Interactive Standardized Crypto Stocks

We reproduced the line plot, where each stock data get standardized, into the interactive form. The reason of standardizing the data is that, some of the chosen stock has much higher price compared to the other. Plotting the stock prices with their original prices would make it hard to observe pattern of trends and relationships among the six cryptos. Thus, we used the standardized data for each stock and plot them together in the same graph.

The graph looks almost the same as the one in the previous section. Users can directly see the standardized number of each stock when moving the mouse along the lines. The numbers can give users better understanding of how much drop/rise in some periods. For example, we can find that even though all six cryptos had a trend of decreasing around October 2018. Among the six cryptos `Doge` dropped the most.

<iframe src="interactives/stockScaled.html" width="900" height="630"></iframe>


## Interactive Single Stock

The second interactive graph is to show the single stock value. There are six tabs on the tops. Users can click on each tab to display the original single stock price. As mentioned previously, the price bases of the cryptos varied a lot. It's meaningless to show their price together in the same graph. Considering people are usually more sensitive. Users can combine the price line with the plot in the last section to gain more understanding of a specific stock. For example, if a person want to invest in `Doge`, he/she can have a overall idea about whether `Doge` usually follows the trends of other cryptos. Also, to further investigate the trend of price of `Doge`, he/she can refer to the single line plot to check the price. 

<iframe src="interactives/stock.html" width="900" height="630"></iframe>